name: nimbus
description: A beautiful e-book reading app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  
  # Firebase (Updated to latest compatible versions)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  
  # PDF Viewer (Using flutter_pdfview - more compatible)
  flutter_pdfview: ^1.3.2
  http: ^1.1.0
  path_provider: ^2.1.1
  
  # State Management & Additional
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  
  # Confetti animation for order confirmation
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true