// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiuCrwBw3W4CCQBpoADbhSjImMUnjQwnQ',
    appId: '1:622647875503:web:7ac9943b4e50d54b06815a',
    messagingSenderId: '622647875503',
    projectId: 'nimbus-ff153',
    authDomain: 'nimbus-ff153.firebaseapp.com',
    storageBucket: 'nimbus-ff153.firebasestorage.app',
    measurementId: 'G-W3VMRD2JLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATNNJgLjmxgnlNCUwHa38ofPpplqxvxJQ',
    appId: '1:622647875503:android:92d6fc020c974ef306815a',
    messagingSenderId: '622647875503',
    projectId: 'nimbus-ff153',
    storageBucket: 'nimbus-ff153.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJTWAlxaPPVepR2qwgfbk8utk0wyXKwHA',
    appId: '1:622647875503:ios:8f7cf41544bfff0606815a',
    messagingSenderId: '622647875503',
    projectId: 'nimbus-ff153',
    storageBucket: 'nimbus-ff153.firebasestorage.app',
    iosClientId: '622647875503-jns0m69rstj2prhkfakn80a359e4pqou.apps.googleusercontent.com',
    iosBundleId: 'com.example.nimbusNew2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJTWAlxaPPVepR2qwgfbk8utk0wyXKwHA',
    appId: '1:622647875503:ios:8f7cf41544bfff0606815a',
    messagingSenderId: '622647875503',
    projectId: 'nimbus-ff153',
    storageBucket: 'nimbus-ff153.firebasestorage.app',
    iosClientId: '622647875503-jns0m69rstj2prhkfakn80a359e4pqou.apps.googleusercontent.com',
    iosBundleId: 'com.example.nimbusNew2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiuCrwBw3W4CCQBpoADbhSjImMUnjQwnQ',
    appId: '1:622647875503:web:ad4de2842c6d422006815a',
    messagingSenderId: '622647875503',
    projectId: 'nimbus-ff153',
    authDomain: 'nimbus-ff153.firebaseapp.com',
    storageBucket: 'nimbus-ff153.firebasestorage.app',
    measurementId: 'G-ZKH0RY98T2',
  );
}
